GET http://{{host}}:{{port}}/api/v1/client/{{id}}
Accept: application/json
Authorization: Bearer {{token}}

###
POST http://{{host}}:{{port}}/api/v1/client
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": {{name}},
  "lastName": {{lastName}},
  "phone": {{phone}}
}