version: "3.8"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@amdin.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "12345:80"
    depends_on:
      - postgres

#  spring:
#    image: yersonargote/restaurant
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SERVER_PORT=8080
#      - SPRING_PROFILES_ACTIVE=docker
#      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
#      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    restart: always